# Generated by Django 5.1.7 on 2025-05-04 08:40

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'organizations',
            },
        ),
        migrations.CreateModel(
            name='League',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
                ('sort_order', models.IntegerField(default=0)),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='teams.organization')),
            ],
            options={
                'db_table': 'leagues',
            },
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='team_logos/')),
                ('sort_order', models.IntegerField(default=0)),
                ('color', models.CharField(blank=True, max_length=50, null=True)),
                ('is_select', models.BooleanField(null=True)),
                ('usukoi_parameter', models.CharField(blank=True, max_length=50, null=True, verbose_name='日本プロ野球記録')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('league', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teams.league')),
            ],
            options={
                'db_table': 'teams',
                'ordering': ['league', 'sort_order'],
                'indexes': [models.Index(fields=['league'], name='teams_league__adc265_idx')],
            },
        ),
    ]
