# Generated by Django 5.1.7 on 2025-05-24 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0003_teamseason'),
    ]

    operations = [
        migrations.AddField(
            model_name='teamseason',
            name='draw',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='teamseason',
            name='lose',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='teamseason',
            name='match',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='teamseason',
            name='win',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
