# Generated by Django 5.1.7 on 2025-05-28 07:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0004_teamseason_draw_teamseason_lose_teamseason_match_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teamseason',
            name='match',
        ),
    ]
