# Generated by Django 5.1.7 on 2025-05-28 19:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0005_remove_teamseason_match'),
    ]

    operations = [
        migrations.AddField(
            model_name='league',
            name='color',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='league',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='league_logos/'),
        ),
        migrations.AddField(
            model_name='teamseason',
            name='league',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='teams.league'),
        ),
    ]
