# Generated by Django 5.1.7 on 2025-05-04 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('sort_order', models.IntegerField(default=0)),
                ('is_foreign', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'places',
            },
        ),
    ]
