# Generated by Django 5.1.7 on 2025-05-04 08:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('careers', '0001_initial'),
        ('players', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='playercareer',
            name='player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='players.player'),
        ),
        migrations.AddIndex(
            model_name='playercareer',
            index=models.Index(fields=['player', 'sort_order'], name='player_care_player__da7901_idx'),
        ),
    ]
