# Generated by Django 5.1.7 on 2025-05-05 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('careers', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlayerCareerView',
            fields=[
                ('player_career_id', models.IntegerField(primary_key=True, serialize=False)),
                ('career_id', models.IntegerField()),
                ('player_id', models.IntegerField()),
                ('player_name', models.CharField(max_length=50)),
                ('player_furigana', models.CharField(blank=True, max_length=50, null=True)),
                ('player_birthday', models.DateField(blank=True, null=True)),
                ('after_career_id', models.IntegerField()),
                ('after_career_name', models.CharField(max_length=50)),
                ('draft_year', models.IntegerField()),
                ('team_logo', models.ImageField(blank=True, null=True, upload_to='team_logos/')),
                ('draft_category_name', models.CharField(max_length=50)),
                ('player_draft_rank', models.IntegerField()),
                ('player_draft_miss_count', models.IntegerField()),
            ],
            options={
                'db_table': 'player_careers_view',
                'managed': False,
            },
        ),
    ]
