# Generated by Django 5.1.7 on 2025-05-14 07:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seasons', '0001_initial'),
        ('teams', '0002_alter_league_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='season',
            name='label',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='season',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='teams.organization'),
        ),
    ]
