# Generated by Django 5.1.7 on 2025-05-14 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seasons', '0002_season_label_season_organization'),
    ]

    operations = [
        migrations.AddField(
            model_name='season',
            name='sort_order',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
