# Generated by Django 5.1.7 on 2025-05-14 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('titles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlayerLatestTitleView',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('team_id', models.IntegerField(blank=True, null=True)),
                ('title_id', models.IntegerField(blank=True, null=True)),
                ('year', models.IntegerField(blank=True, null=True)),
                ('player_id', models.IntegerField(blank=True, null=True)),
                ('player_name', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'player_latest_title_view',
                'managed': False,
            },
        ),
    ]
