# Generated by Django 5.1.7 on 2025-05-19 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('titles', '0003_playertitle_season'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlayerTitleView',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('title_id', models.IntegerField(blank=True, null=True)),
                ('position_id', models.IntegerField(blank=True, null=True)),
                ('year', models.IntegerField(blank=True, null=True)),
                ('season_label', models.CharField(blank=True, max_length=50, null=True)),
                ('team_logo', models.ImageField(blank=True, null=True, upload_to='team_logos/')),
                ('player_id', models.IntegerField(blank=True, null=True)),
                ('player_name', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'player_title_view',
                'managed': False,
            },
        ),
    ]
