# Generated by Django 5.1.7 on 2025-05-26 02:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('players', '0002_playercategory_player_player_category'),
        ('teams', '0004_teamseason_draw_teamseason_lose_teamseason_match_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'transfers',
            },
        ),
        migrations.CreateModel(
            name='TransferType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
            ],
            options={
                'db_table': 'transfer_types',
            },
        ),
        migrations.CreateModel(
            name='PlayerTransfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='transfers_from', to='teams.teamseason')),
                ('player', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='players.player')),
                ('to_team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='transfers_to', to='teams.teamseason')),
                ('transfer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='transfers.transfer')),
            ],
            options={
                'db_table': 'player_transfers',
            },
        ),
        migrations.AddField(
            model_name='transfer',
            name='transfer_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='transfers.transfertype'),
        ),
    ]
