# Generated by Django 5.1.7 on 2025-05-14 07:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0001_initial'),
        ('seasons', '0002_season_label_season_organization'),
    ]

    operations = [
        migrations.AddField(
            model_name='playerbattingrecord',
            name='season',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='seasons.season'),
        ),
        migrations.AddField(
            model_name='playercommonrecord',
            name='season',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='seasons.season'),
        ),
        migrations.AddField(
            model_name='playerfieldingrecord',
            name='season',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='seasons.season'),
        ),
        migrations.AddField(
            model_name='playerpitchingrecord',
            name='season',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='seasons.season'),
        ),
    ]
