# Generated by Django 5.1.7 on 2025-05-24 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0002_playerbattingrecord_season_playercommonrecord_season_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlayerSalaryView',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('year', models.IntegerField()),
                ('player_id', models.IntegerField()),
                ('player_name', models.CharField(blank=True, max_length=50, null=True)),
                ('team_logo', models.ImageField(blank=True, null=True, upload_to='team_logos/')),
                ('salary', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('rank', models.IntegerField()),
            ],
            options={
                'db_table': 'player_salary_view',
                'managed': False,
            },
        ),
    ]
