# Generated by Django 5.1.7 on 2025-05-26 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0003_playersalaryview'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playercommonrecord',
            name='year',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
