# Generated by Django 5.1.7 on 2025-06-25 03:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0004_alter_playercommonrecord_year'),
        ('teams', '0006_league_color_league_logo_teamseason_league'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playercommonrecord',
            name='team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='teams.team'),
        ),
    ]
