# Generated by Django 5.1.7 on 2025-06-27 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0005_alter_playercommonrecord_team'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playerbattingrecord',
            name='year',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='playerfieldingrecord',
            name='year',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='playerpitchingrecord',
            name='year',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
