# Generated by Django 5.1.7 on 2025-05-24 02:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('stadiums', '0001_initial'),
        ('teams', '0003_teamseason'),
    ]

    operations = [
        migrations.CreateModel(
            name='GameStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
            ],
            options={
                'db_table': 'game_status',
            },
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('start_time', models.TimeField(blank=True, null=True)),
                ('home_score', models.IntegerField(blank=True, null=True)),
                ('away_score', models.IntegerField(blank=True, null=True)),
                ('remarks', models.CharField(max_length=50)),
                ('away_team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='away_games', to='teams.teamseason')),
                ('home_team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='home_games', to='teams.teamseason')),
                ('stadium', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='stadiums.stadium')),
                ('game_status', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='games.gamestatus')),
            ],
            options={
                'db_table': 'games',
            },
        ),
    ]
