# Generated by Django 5.1.7 on 2025-05-24 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='remarks',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
