# Generated by Django 5.1.7 on 2025-03-24 00:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='player',
            table='players',
        ),
    ]
