# Generated by Django 5.1.7 on 2025-06-19 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0002_playercategory_player_player_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='birth_year',
            field=models.IntegerField(blank=True, null=True, verbose_name='誕生年'),
        ),
        migrations.AddField(
            model_name='player',
            name='death_date',
            field=models.DateField(blank=True, null=True, verbose_name='没年月日'),
        ),
        migrations.AddField(
            model_name='player',
            name='is_dead',
            field=models.BooleanField(blank=True, null=True, verbose_name='死去'),
        ),
    ]
