# Generated by Django 5.1.7 on 2025-03-24 01:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0004_league_alter_player_name'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='league',
            table='leagues',
        ),
    ]
