# Generated by Django 5.1.7 on 2025-03-24 01:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0007_team'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='team',
            table='teams',
        ),
    ]
