# Generated by Django 5.1.7 on 2025-03-24 03:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0009_handbatting_handthrowing_player_birth_month_and_more'),
    ]

    operations = [
    ]
