# Generated by Django 5.1.7 on 2025-03-24 04:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0012_alter_player_created_at_alter_player_updated_at_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='currency',
            table='currencies',
        ),
        migrations.AlterModelTable(
            name='exchangerate',
            table='exchange_rates',
        ),
        migrations.AlterModelTable(
            name='handbatting',
            table='hands_batting',
        ),
        migrations.AlterModelTable(
            name='handthrowing',
            table='hands_throwing',
        ),
        migrations.AlterModelTable(
            name='place',
            table='places',
        ),
        migrations.AlterModelTable(
            name='playercommonrecord',
            table='player_common_records',
        ),
        migrations.AlterModelTable(
            name='positioncategory',
            table='position_categories',
        ),
    ]
