# Generated by Django 5.1.7 on 2025-03-24 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0013_alter_currency_table_alter_exchangerate_table_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playercommonrecord',
            name='number',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
    ]
