# Generated by Django 5.1.7 on 2025-03-24 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0014_alter_playercommonrecord_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playercommonrecord',
            name='salary',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
    ]
