# Generated by Django 5.1.7 on 2025-03-24 12:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0015_alter_playercommonrecord_salary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playercommonrecord',
            name='currency',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='players.currency'),
        ),
    ]
