# Generated by Django 5.1.7 on 2025-03-26 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0016_alter_playercommonrecord_currency'),
    ]

    operations = [
        migrations.AddField(
            model_name='currency',
            name='symbol',
            field=models.CharField(default='', max_length=10),
        ),
    ]
