# Generated by Django 5.1.7 on 2025-04-01 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0020_alter_team_league'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='is_married',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
