# Generated by Django 5.1.7 on 2025-04-08 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0022_position_playerbattingrecord_playerpitchinigrecord_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playerpitchingrecord',
            name='innings_pitched',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=10, null=True),
        ),
    ]
