# Generated by Django 5.1.7 on 2025-04-09 01:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0023_alter_playerpitchingrecord_innings_pitched'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='playerbattingrecord',
            name='errors',
        ),
    ]
