# Generated by Django 5.1.7 on 2025-04-09 01:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0024_remove_playerbattingrecord_errors'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='playerfieldingrecord',
            unique_together={('player', 'year', 'position')},
        ),
    ]
