# Generated by Django 5.1.7 on 2025-04-09 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0025_alter_playerfieldingrecord_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='team_logos/'),
        ),
    ]
