# Generated by Django 5.1.7 on 2025-04-17 05:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0028_careercategory_career_playercareer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='playercareer',
            name='career',
        ),
        migrations.AddField(
            model_name='career',
            name='wikipedia_parameter',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.CreateModel(
            name='CareerVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('version', models.IntegerField(default=0)),
                ('career', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='players.career')),
            ],
            options={
                'db_table': 'career_version',
            },
        ),
        migrations.AddField(
            model_name='playercareer',
            name='career_version',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='players.careerversion'),
        ),
    ]
