# Generated by Django 5.1.7 on 2025-04-17 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0029_remove_playercareer_career_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='playercareer',
            name='remarks',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
