# Generated by Django 5.1.7 on 2025-04-17 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0030_playercareer_remarks'),
    ]

    operations = [
        migrations.RenameField(
            model_name='career',
            old_name='wikipedia_parameter',
            new_name='wikipedia_parameter1',
        ),
        migrations.AddField(
            model_name='career',
            name='wikipedia_parameter2',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
