# Generated by Django 5.1.7 on 2025-04-20 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0031_rename_wikipedia_parameter_career_wikipedia_parameter1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='careercategory',
            name='label',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
