# Generated by Django 5.1.7 on 2025-04-20 23:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0032_careercategory_label'),
    ]

    operations = [
        migrations.CreateModel(
            name='DraftCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('sort_order', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'draft_categories',
            },
        ),
        migrations.CreateModel(
            name='Title',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('sort_order', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'titles',
            },
        ),
        migrations.CreateModel(
            name='Draft',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('draft_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='players.draftcategory')),
            ],
            options={
                'db_table': 'drafts',
            },
        ),
        migrations.CreateModel(
            name='PlayerDraft',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('rank', models.IntegerField()),
                ('is_reverse_nomination', models.BooleanField(blank=True, null=True)),
                ('is_hit', models.BooleanField(blank=True, null=True)),
                ('miss_count', models.IntegerField()),
                ('is_joined', models.BooleanField(blank=True, null=True)),
                ('draft', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='players.draft')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='players.player')),
                ('position_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='players.positioncategory')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='players.team')),
            ],
            options={
                'db_table': 'player_drafts',
            },
        ),
        migrations.CreateModel(
            name='PlayerTitle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='players.player')),
                ('position', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='players.position')),
                ('title', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='players.title')),
            ],
            options={
                'db_table': 'player_titles',
            },
        ),
    ]
