# Generated by Django 5.1.7 on 2025-04-21 01:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0033_draftcategory_title_draft_playerdraft_playertitle'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='playerdraft',
            name='year',
        ),
    ]
