# Generated by Django 5.1.7 on 2025-04-21 02:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0034_remove_playerdraft_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='position',
            name='position_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='players.positioncategory'),
        ),
    ]
