# Generated by Django 5.1.7 on 2025-04-21 02:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0035_alter_position_position_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playertitle',
            name='position',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='players.position'),
        ),
    ]
