# Generated by Django 5.1.7 on 2025-04-21 12:22

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0036_alter_playertitle_position'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='birth_month',
        ),
        migrations.RemoveField(
            model_name='player',
            name='birth_year',
        ),
        migrations.AlterField(
            model_name='player',
            name='batting_hand',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='players.handbatting', verbose_name='利腕'),
        ),
        migrations.AlterField(
            model_name='player',
            name='birthday',
            field=models.DateField(blank=True, null=True, verbose_name='誕生日'),
        ),
        migrations.AlterField(
            model_name='player',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='作成日時'),
        ),
        migrations.AlterField(
            model_name='player',
            name='favorite_team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='players.team', verbose_name='ファン球団'),
        ),
        migrations.AlterField(
            model_name='player',
            name='furigana',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='ふりがな'),
        ),
        migrations.AlterField(
            model_name='player',
            name='height',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='身長'),
        ),
        migrations.AlterField(
            model_name='player',
            name='hobby',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='趣味'),
        ),
        migrations.AlterField(
            model_name='player',
            name='is_married',
            field=models.BooleanField(blank=True, null=True, verbose_name='結婚'),
        ),
        migrations.AlterField(
            model_name='player',
            name='main_position_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='players.positioncategory', verbose_name='ポジション'),
        ),
        migrations.AlterField(
            model_name='player',
            name='name',
            field=models.CharField(max_length=50, verbose_name='氏名'),
        ),
        migrations.AlterField(
            model_name='player',
            name='nickname',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='通称'),
        ),
        migrations.AlterField(
            model_name='player',
            name='partner',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='結婚相手'),
        ),
        migrations.AlterField(
            model_name='player',
            name='place',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='players.place', verbose_name='出身地'),
        ),
        migrations.AlterField(
            model_name='player',
            name='remarks',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='備考'),
        ),
        migrations.AlterField(
            model_name='player',
            name='specialty',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='特技'),
        ),
        migrations.AlterField(
            model_name='player',
            name='throwing_hand',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='players.handthrowing', verbose_name='利腕'),
        ),
        migrations.AlterField(
            model_name='player',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='更新日時'),
        ),
        migrations.AlterField(
            model_name='player',
            name='usukoi_parameter',
            field=models.IntegerField(blank=True, null=True, verbose_name='日本プロ野球記録'),
        ),
        migrations.AlterField(
            model_name='player',
            name='weight',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='体重'),
        ),
        migrations.AlterField(
            model_name='player',
            name='wikipedia_parameter',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Wikipedia'),
        ),
        migrations.AlterField(
            model_name='player',
            name='youtube_parameter',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='YouTube'),
        ),
    ]
