# Generated by Django 5.1.7 on 2025-04-23 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0037_remove_player_birth_month_remove_player_birth_year_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='playercommonrecord',
            options={'ordering': ['year']},
        ),
        migrations.AddIndex(
            model_name='playercareer',
            index=models.Index(fields=['player', 'sort_order'], name='player_care_player__d84834_idx'),
        ),
        migrations.AddIndex(
            model_name='team',
            index=models.Index(fields=['league'], name='teams_league__adc265_idx'),
        ),
    ]
