# Generated by Django 5.1.7 on 2025-04-23 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0038_alter_playercommonrecord_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlayerLatestSummary',
            fields=[
                ('player_id', models.IntegerField(primary_key=True, serialize=False)),
                ('player_name', models.CharField(max_length=50, verbose_name='氏名')),
                ('player_furigana', models.CharField(blank=True, max_length=50, null=True, verbose_name='ふりがな')),
                ('player_nickname', models.CharField(blank=True, max_length=50, null=True, verbose_name='通称')),
                ('player_birthday', models.DateField(blank=True, null=True, verbose_name='誕生日')),
                ('player_height', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='身長')),
                ('player_weight', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='体重')),
                ('player_is_married', models.BooleanField(blank=True, null=True, verbose_name='結婚')),
                ('player_partner', models.CharField(blank=True, max_length=50, null=True, verbose_name='結婚相手')),
                ('player_hobby', models.CharField(blank=True, max_length=50, null=True, verbose_name='趣味')),
                ('player_specialty', models.CharField(blank=True, max_length=50, null=True, verbose_name='特技')),
                ('player_wikipedia_parameter', models.CharField(blank=True, max_length=250, null=True, verbose_name='Wikipedia')),
                ('player_usukoi_parameter', models.IntegerField(blank=True, null=True, verbose_name='日本プロ野球記録')),
                ('player_youtube_parameter', models.CharField(blank=True, max_length=250, null=True, verbose_name='YouTube')),
                ('player_remarks', models.CharField(blank=True, max_length=250, null=True, verbose_name='備考')),
                ('place_id', models.IntegerField()),
                ('place_name', models.CharField(max_length=10)),
                ('throwing_id', models.IntegerField()),
                ('throwing_name', models.CharField(max_length=10)),
                ('batting_id', models.IntegerField()),
                ('batting_name', models.CharField(max_length=10)),
                ('position_category_id', models.IntegerField()),
                ('position_category_name', models.CharField(max_length=50)),
                ('position_category_sort_order', models.IntegerField(default=0)),
                ('player_career_remarks', models.CharField(blank=True, max_length=50, null=True)),
                ('career_version_id', models.IntegerField()),
                ('career_version_name', models.CharField(max_length=50)),
                ('career_category_id', models.IntegerField()),
                ('career_category_label', models.CharField(max_length=10)),
                ('player_draft_rank', models.IntegerField()),
                ('player_draft_miss_count', models.IntegerField()),
                ('draft_year', models.IntegerField()),
                ('draft_category_name', models.CharField(max_length=50)),
                ('common_record_year', models.IntegerField()),
                ('common_record_number', models.CharField(blank=True, max_length=5, null=True)),
                ('common_record_registered_name', models.CharField(blank=True, max_length=50, null=True)),
                ('common_record_salary', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('currency_name', models.CharField(max_length=30)),
                ('team_logo', models.ImageField(blank=True, null=True, upload_to='team_logos/')),
                ('team_order', models.IntegerField(default=0)),
                ('team_color', models.CharField(blank=True, max_length=50, null=True)),
                ('league_order', models.IntegerField()),
                ('pitching_year', models.IntegerField()),
                ('pitching_games', models.IntegerField(blank=True, null=True)),
                ('pitching_wins', models.IntegerField(blank=True, null=True)),
                ('pitching_loses', models.IntegerField(blank=True, null=True)),
                ('pitching_saves', models.IntegerField(blank=True, null=True)),
                ('pitching_holds', models.IntegerField(blank=True, null=True)),
                ('pitching_strike_outs', models.IntegerField(blank=True, null=True)),
                ('pitching_earned_run_average', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('batting_year', models.IntegerField()),
                ('batting_plate_appearances', models.IntegerField(blank=True, null=True)),
                ('batting_home_runs', models.IntegerField(blank=True, null=True)),
                ('batting_runs_batted_in', models.IntegerField(blank=True, null=True)),
                ('batting_stolen_bases', models.IntegerField(blank=True, null=True)),
                ('batting_average', models.DecimalField(blank=True, decimal_places=3, max_digits=4, null=True)),
            ],
            options={
                'db_table': 'player_latest_summary',
                'managed': False,
            },
        ),
    ]
