# Generated by Django 5.1.7 on 2025-04-24 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0039_playerlatestsummary'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='is_select',
            field=models.BooleanField(null=True),
        ),
    ]
