# Generated by Django 5.1.7 on 2025-04-26 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0040_team_is_select'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='usukoi_parameter',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='日本プロ野球記録'),
        ),
    ]
