INSERT INTO player_titles (year, player_id, title_id, season_id) VALUES (0, 804, 5, 239);
INSERT INTO player_titles (year, player_id, title_id, season_id) VALUES (0, 450, 5, 239);
INSERT INTO player_titles (year, player_id, title_id, season_id) VALUES (0, 21, 7, 239);
INSERT INTO player_titles (year, player_id, title_id, season_id) VALUES (0, 736, 7, 239);
INSERT INTO player_titles (year, player_id, title_id, season_id) VALUES (0, 175, 3, 239);
INSERT INTO player_titles (year, player_id, title_id, season_id) VALUES (0, 450, 3, 239);
INSERT INTO player_titles (year, player_id, title_id, season_id) VALUES (0, 315, 1, 239);
INSERT INTO player_titles (year, player_id, title_id, season_id) VALUES (0, 437, 1, 239);
INSERT INTO player_titles (year, player_id, title_id, season_id) VALUES (0, 315, 4, 239);
INSERT INTO player_titles (year, player_id, title_id, season_id) VALUES (0, 437, 4, 239);
INSERT INTO player_titles (year, player_id, title_id, season_id) VALUES (0, 121, 9, 239);
INSERT INTO player_titles (year, player_id, title_id, season_id) VALUES (0, 440, 9, 239);
INSERT INTO player_titles (year, player_id, title_id, season_id) VALUES (0, 322, 10, 239);
INSERT INTO player_titles (year, player_id, title_id, season_id) VALUES (0, 450, 10, 239);
INSERT INTO player_titles (year, player_id, title_id, season_id) VALUES (0, 307, 11, 239);
INSERT INTO player_titles (year, player_id, title_id, season_id) VALUES (0, 652, 11, 239);
INSERT INTO player_titles (year, player_id, title_id, season_id) VALUES (0, 804, 12, 239);
INSERT INTO player_titles (year, player_id, title_id, season_id) VALUES (0, 400, 12, 239);
INSERT INTO player_titles (year, player_id, title_id, season_id) VALUES (0, 463, 12, 239);
INSERT INTO player_titles (year, player_id, title_id, season_id) VALUES (0, 334, 13, 239);
INSERT INTO player_titles (year, player_id, title_id, season_id) VALUES (0, 407, 13, 239);
INSERT INTO player_titles (year, player_id, title_id, season_id) VALUES (0, 804, 14, 239);
INSERT INTO player_titles (year, player_id, title_id, season_id) VALUES (0, 463, 14, 239);
INSERT INTO player_titles (year, player_id, title_id, season_id) VALUES (0, 5, 15, 239);
INSERT INTO player_titles (year, player_id, title_id, season_id) VALUES (0, 748, 15, 239);
INSERT INTO player_titles (year, player_id, title_id, season_id) VALUES (0, 29, 16, 239);
INSERT INTO player_titles (year, player_id, title_id, season_id) VALUES (0, 595, 16, 239);
INSERT INTO player_titles (year, player_id, title_id, season_id) VALUES (0, 84, 17, 239);
INSERT INTO player_titles (year, player_id, title_id, season_id) VALUES (0, 357, 17, 239);
INSERT INTO player_titles (year, player_id, title_id, season_id) VALUES (0, 471, 17, 239);
INSERT INTO player_titles (year, player_id, position_id, title_id, season_id) VALUES (0, 804, 1, 8, 239);
INSERT INTO player_titles (year, player_id, position_id, title_id, season_id) VALUES (0, 170, 2, 8, 239);
INSERT INTO player_titles (year, player_id, position_id, title_id, season_id) VALUES (0, 45, 3, 8, 239);
INSERT INTO player_titles (year, player_id, position_id, title_id, season_id) VALUES (0, 41, 4, 8, 239);
INSERT INTO player_titles (year, player_id, position_id, title_id, season_id) VALUES (0, 315, 5, 8, 239);
INSERT INTO player_titles (year, player_id, position_id, title_id, season_id) VALUES (0, 307, 6, 8, 239);
INSERT INTO player_titles (year, player_id, position_id, title_id, season_id) VALUES (0, 322, 7, 8, 239);
INSERT INTO player_titles (year, player_id, position_id, title_id, season_id) VALUES (0, 392, 7, 8, 239);
INSERT INTO player_titles (year, player_id, position_id, title_id, season_id) VALUES (0, 121, 7, 8, 239);
INSERT INTO player_titles (year, player_id, position_id, title_id, season_id) VALUES (0, 400, 1, 8, 239);
INSERT INTO player_titles (year, player_id, position_id, title_id, season_id) VALUES (0, 564, 2, 8, 239);
INSERT INTO player_titles (year, player_id, position_id, title_id, season_id) VALUES (0, 437, 3, 8, 239);
INSERT INTO player_titles (year, player_id, position_id, title_id, season_id) VALUES (0, 635, 4, 8, 239);
INSERT INTO player_titles (year, player_id, position_id, title_id, season_id) VALUES (0, 441, 5, 8, 239);
INSERT INTO player_titles (year, player_id, position_id, title_id, season_id) VALUES (0, 438, 6, 8, 239);
INSERT INTO player_titles (year, player_id, position_id, title_id, season_id) VALUES (0, 652, 7, 8, 239);
INSERT INTO player_titles (year, player_id, position_id, title_id, season_id) VALUES (0, 450, 7, 8, 239);
INSERT INTO player_titles (year, player_id, position_id, title_id, season_id) VALUES (0, 440, 7, 8, 239);
INSERT INTO player_titles (year, player_id, position_id, title_id, season_id) VALUES (0, 525, 8, 8, 239);
INSERT INTO player_titles (year, player_id, position_id, title_id, season_id) VALUES (0, 804, 1, 6, 239);
INSERT INTO player_titles (year, player_id, position_id, title_id, season_id) VALUES (0, 170, 2, 6, 239);
INSERT INTO player_titles (year, player_id, position_id, title_id, season_id) VALUES (0, 45, 3, 6, 239);
INSERT INTO player_titles (year, player_id, position_id, title_id, season_id) VALUES (0, 41, 4, 6, 239);
INSERT INTO player_titles (year, player_id, position_id, title_id, season_id) VALUES (0, 43, 5, 6, 239);
INSERT INTO player_titles (year, player_id, position_id, title_id, season_id) VALUES (0, 238, 6, 6, 239);
INSERT INTO player_titles (year, player_id, position_id, title_id, season_id) VALUES (0, 252, 7, 6, 239);
INSERT INTO player_titles (year, player_id, position_id, title_id, season_id) VALUES (0, 384, 7, 6, 239);
INSERT INTO player_titles (year, player_id, position_id, title_id, season_id) VALUES (0, 121, 7, 6, 239);
INSERT INTO player_titles (year, player_id, position_id, title_id, season_id) VALUES (0, 407, 1, 6, 239);
INSERT INTO player_titles (year, player_id, position_id, title_id, season_id) VALUES (0, 32, 2, 6, 239);
INSERT INTO player_titles (year, player_id, position_id, title_id, season_id) VALUES (0, 437, 3, 6, 239);
INSERT INTO player_titles (year, player_id, position_id, title_id, season_id) VALUES (0, 635, 4, 6, 239);
INSERT INTO player_titles (year, player_id, position_id, title_id, season_id) VALUES (0, 441, 5, 6, 239);
INSERT INTO player_titles (year, player_id, position_id, title_id, season_id) VALUES (0, 767, 6, 6, 239);
INSERT INTO player_titles (year, player_id, position_id, title_id, season_id) VALUES (0, 652, 7, 6, 239);
INSERT INTO player_titles (year, player_id, position_id, title_id, season_id) VALUES (0, 440, 7, 6, 239);
INSERT INTO player_titles (year, player_id, position_id, title_id, season_id) VALUES (0, 523, 7, 6, 239);