# Generated by Django 5.1.7 on 2025-05-05 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drafts', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlayerDraftView',
            fields=[
                ('player_draft_id', models.IntegerField(primary_key=True, serialize=False)),
                ('player_draft_rank', models.IntegerField()),
                ('player_draft_is_reverse_nomination', models.BooleanField(null=True)),
                ('player_draft_is_hit', models.BooleanField(null=True)),
                ('player_draft_miss_count', models.IntegerField()),
                ('player_draft_is_joined', models.BooleanField(null=True)),
                ('draft_id', models.IntegerField()),
                ('draft_year', models.IntegerField()),
                ('draft_category_name', models.CharField(max_length=50)),
                ('draft_category_order', models.IntegerField()),
                ('player_id', models.IntegerField()),
                ('player_name', models.CharField(max_length=50)),
                ('position_name', models.CharField(max_length=50)),
                ('team_logo', models.ImageField(blank=True, null=True, upload_to='team_logos/')),
                ('team_order', models.IntegerField()),
                ('league_order', models.IntegerField()),
            ],
            options={
                'db_table': 'player_drafts_view',
                'managed': False,
            },
        ),
    ]
